config/routes.rb
Rails.application.routes.draw do

  root to: 'landing_page#index'

  namespace :guest do
    get '/auth/login', to: 'guests#index', as: 'auth_login'
    post '/access-account', to: 'guests#access_account'
  end

  namespace :dashboard do
    get '/', to: 'home#index'

    post 'auth/sign_out', to: 'home#sign_out', as: 'sign_out'

    # users
    get '/user/edit', to: 'users#edit', as: 'user_edit'
    post '/user/update', to: 'users#update', as: 'user_update'
    post '/user/become_artist', to: 'users#convert_user_to_artist', as: 'convert_user_to_artist'

    get '/proposals', to: 'proposals#index', as: 'proposals'
    get '/proposals/new', to: 'proposals#new', as: 'new_proposals'

    post '/proposals/create', to: 'proposals#create', as: 'create_proposals'
    get '/proposals/edit/:id', to: 'proposals#edit', as: 'edit_proposals'
    post '/proposals/update', to: 'proposals#update', as: 'update_proposals'

    get '/musics', to: 'musics#index', as: 'musics'
    get '/musics/new', to: 'musics#new', as: 'new_music'
    post '/musics/create', to: 'musics#create', as: 'create_music'
    get '/musics/edit/:id', to: 'musics#edit', as: 'edit_music'
    post '/musics/update', to: 'musics#update', as: 'update_music'
  end

end

app/controllers/guest/guests_controller.rb
class Guest::GuestsController < ApplicationController

  before_action :redirect_to_dashboard, only: :index
  skip_before_action :authenticate_user!, only: [:index, :access_account]

  def index
    render_login_page
  end

  def access_account
    begin
      allowed_parameters = filter_params
      user_service = Firebase::Firestore::UserService.new(allowed_parameters)
      firebase_user = user_service.access_account
      user_session(firebase_user['localId'])
      current_user

      redirect_to dashboard_url
    rescue => error
      flash[:danger] = error.message
      render_login_page
    end
  end

  private

  def filter_params
    params.permit(:email, :password)
  end

  def render_login_page
    render 'guests/index'
  end

  def redirect_to_dashboard
    redirect_to dashboard_url if is_logged?
  end
end

app/helpers/guest_helper.rb
module GuestHelper
end

app/views/guests/_footer.html.erb
<footer class="py-5">
    <div class="container">
      <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
          <div class="copyright text-center text-xl-left text-muted">
            &copy; 2019 Voyce
          </div>
        </div>
        <div class="col-xl-6">
          <ul class="nav nav-footer justify-content-center justify-content-xl-end">
            <li class="nav-item">
              <a href="#" class="nav-link" target="_blank">Sobre nós</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" target="_blank">Política de Privacidade</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
</footer>

app/views/guests/_navbar.html.erb
<nav class="navbar navbar-top navbar-horizontal navbar-expand-md navbar-dark">
  <div class="container px-4 mb-4">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-collapse-main">
      <div class="navbar-collapse-header d-md-none">
        <div class="row">
          <div class="col-6 collapse-brand">
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="btn btn-primary mx-5 my-2" href="<%= guest_auth_login_path %>">
            <%= I18n.t('guest.login.buttons.login') %>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/guests/index.html.erb
<%= render 'guests/navbar' %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-5 col-md-7">
      <div class="card bg-secondary shadow border-0">
        <div class="card-body px-lg-5 py-lg-5">
          <div class="text-center mb-4">
            <h2><%= I18n.t('guest.login.titles.login_card_title') %></h2>
          </div>

          <%= render 'layouts/messages' %>

          <%= form_with(url: guest_access_account_path, method: "post") do %>

            <div class="form-group mb-3">
              <div class="input-group input-group-alternative">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fas fa-envelope"></i>
                  </span>
                </div>
                <input class="form-control" placeholder="<%= I18n.t('guest.login.fields.email') %>" type="email" name="email" required autofocus>
              </div>
            </div>

            <br>

            <div class="form-group">
              <div class="input-group input-group-alternative">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fas fa-key"></i>
                  </span>
                </div>
                <input class="form-control" name="password" placeholder="<%= I18n.t('guest.login.fields.password') %>" type="password" value="" required>
              </div>
            </div>

            <div class="text-center">
              <%= button_tag I18n.t('guest.login.buttons.login'), class: "btn btn-primary my-4" %>
            </div>

          <% end %>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col-7">
<!--          <a href="#" class="text-light">-->
<!--            <small>-->
              <%#= I18n.t('guest.login.buttons.forgot_password') %>
<!--            </small>-->
<!--          </a>-->
        </div>
        <div class="col-5 text-right">
<!--          <a href="#" class="text-light">-->
<!--            <small>-->
              <%#= I18n.t('guest.login.fields.like_app_message') %>
<!--            </small>-->
<!--          </a>-->
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'guests/footer' %>

app/views/guests/privacy_policy.html.erb
<h2>Política de privacidade para <a href='http://voyce.com'>Voyce</a></h2>
<p>Todas as suas informações pessoais recolhidas, serão usadas para o ajudar a tornar a sua visita no nosso site o mais produtiva e agradável possível.</p>
<p>A garantia da confidencialidade dos dados pessoais dos utilizadores do nosso site é importante para o Voyce.</p>
<p>Todas as informações pessoais relativas a membros, assinantes, clientes ou visitantes que usem o Voyce serão tratadas em concordância com a Lei da Proteção de Dados Pessoais de 26 de outubro de 1998 (Lei n.º 67/98).</p>
<p>A informação pessoal recolhida pode incluir o seu nome, e-mail, número de telefone e/ou telemóvel, morada, data de nascimento e/ou outros.</p>
<p>O uso do Voyce pressupõe a aceitação deste Acordo de privacidade. A equipa do Voyce reserva-se ao direito de alterar este acordo sem aviso prévio. Deste modo, recomendamos que consulte a nossa política de privacidade com regularidade de forma a estar sempre atualizado.</p>
<h2>Os anúncios</h2>
<p>Tal como outros websites, coletamos e utilizamos informação contida nos anúncios. A informação contida nos anúncios, inclui o seu endereço IP (Internet Protocol), o seu ISP (Internet Service Provider, como o Sapo, Clix, ou outro), o browser que utilizou ao visitar o nosso website (como o Internet Explorer ou o Firefox), o tempo da sua visita e que páginas visitou dentro do nosso website.</p>
<h2>Cookie DoubleClick Dart</h2>
<p>O Google, como fornecedor de terceiros, utiliza cookies para exibir anúncios no nosso website;</p>
<p>Com o cookie DART, o Google pode exibir anúncios com base nas visitas que o leitor fez a outros websites na Internet;</p>
<p>Os utilizadores podem desativar o cookie DART visitando a Política de <a href='http://politicaprivacidade.com/' title='privacidade da rede de conteúdo'>privacidade da rede de conteúdo</a> e dos anúncios do Google.</p>
<h2>Os Cookies e Web Beacons</h2>
<p>Utilizamos cookies para armazenar informação, tais como as suas preferências pessoas quando visita o nosso website. Isto poderá incluir um simples popup, ou uma ligação em vários serviços que providenciamos, tais como fóruns.</p>
<p>Em adição também utilizamos publicidade de terceiros no nosso website para suportar os custos de manutenção. Alguns destes publicitários, poderão utilizar tecnologias como os cookies e/ou web beacons quando publicitam no nosso website, o que fará com que esses publicitários (como o Google através do Google AdSense) também recebam a sua informação pessoal, como o endereço IP, o seu ISP, o seu browser, etc. Esta função é geralmente utilizada para geotargeting (mostrar publicidade de Lisboa apenas aos leitores oriundos de Lisboa por ex.) ou apresentar publicidade direcionada a um tipo de utilizador (como mostrar publicidade de restaurante a um utilizador que visita sites de culinária regularmente, por ex.).</p>
<p>Você detém o poder de desligar os seus cookies, nas opções do seu browser, ou efetuando alterações nas ferramentas de programas Anti-Virus, como o Norton Internet Security. No entanto, isso poderá alterar a forma como interage com o nosso website, ou outros websites. Isso poderá afetar ou não permitir que faça logins em programas, sites ou fóruns da nossa e de outras redes.</p>
<h2>Ligações a Sites de terceiros</h2>
<p>O Voyce possui ligações para outros sites, os quais, a nosso ver, podem conter informações / ferramentas úteis para os nossos visitantes. A nossa política de privacidade não é aplicada a sites de terceiros, pelo que, caso visite outro site a partir do nosso deverá ler a politica de privacidade do mesmo.</p>
<p>Não nos responsabilizamos pela política de privacidade ou conteúdo presente nesses mesmos sites.</p>