config/routes.rb
Rails.application.routes.draw do

  root to: 'landing_page#index'

  namespace :guest do
    get '/auth/login', to: 'guests#index', as: 'auth_login'
    post '/access-account', to: 'guests#access_account'
  end

  namespace :dashboard do
    get '/', to: 'home#index'

    post 'auth/sign_out', to: 'home#sign_out', as: 'sign_out'

    # users
    get '/user/edit', to: 'users#edit', as: 'user_edit'
    post '/user/update', to: 'users#update', as: 'user_update'
    post '/user/become_artist', to: 'users#convert_user_to_artist', as: 'convert_user_to_artist'

    get '/proposals', to: 'proposals#index', as: 'proposals'
    get '/proposals/new', to: 'proposals#new', as: 'new_proposals'

    post '/proposals/create', to: 'proposals#create', as: 'create_proposals'
    get '/proposals/edit/:id', to: 'proposals#edit', as: 'edit_proposals'
    post '/proposals/update', to: 'proposals#update', as: 'update_proposals'

    get '/musics', to: 'musics#index', as: 'musics'
    get '/musics/new', to: 'musics#new', as: 'new_music'
    post '/musics/create', to: 'musics#create', as: 'create_music'
    get '/musics/edit/:id', to: 'musics#edit', as: 'edit_music'
    post '/musics/update', to: 'musics#update', as: 'update_music'
  end

end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController

  def index
    begin
      music_service = Firebase::Firestore::MusicService.new(user_id: current_user[:id])
      all_songs = music_service.load_all_songs
      @singles = all_songs[:singles]
      @albuns = all_songs[:albuns]
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def sign_out
    reset_session

    redirect_to guest_auth_login_path
  end

end

app/controllers/dashboard/musics_controller.rb
class Dashboard::MusicsController < ApplicationController

  def index
    begin
      music_service = Firebase::Firestore::MusicService.new(user_id: current_user[:id])
      all_songs = music_service.load_all_songs
      @singles = all_songs[:singles]
      @albuns = all_songs[:albuns]
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def new
  end

  def create
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      music_service = Firebase::Firestore::MusicService.new(allowed_parameters)
      music_service.process_creation

      flash[:success] = I18n.t('dashboard.musics.messages.success_on_create')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_musics_url
  end

  def edit
    begin
      music_params = { music_id: params[:id], user_id: current_user[:id] }
      music_service = Firebase::Firestore::MusicService.new(music_params)
      @song = music_service.load_song

      flash[:warning] = I18n.t('dashboard.musics.messages.alert_edit_music')
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def update
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      music_service = Firebase::Firestore::MusicService.new(allowed_parameters)
      music_service.process_update

      flash[:success] = I18n.t('dashboard.musics.messages.success_on_update')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_musics_url
  end

  private

  def filter_params
    params.permit(:music_title, :music_file, :number_track, :image_cover, :music_id)
  end

end

app/controllers/dashboard/proposals_controller.rb
class Dashboard::ProposalsController < ApplicationController

  def index
    begin
      proposal_service = Firebase::Firestore::ProposalService.new(user_id: current_user[:id])
      @all_proposals = proposal_service.load_all_proposals
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def new
  end

  def create
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      proposal_service = Firebase::Firestore::ProposalService.new(allowed_parameters)
      proposal_service.process_creation

      flash[:success] = I18n.t('dashboard.proposals.messages.success_on_create')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_proposals_url
  end

  def edit
    begin
      params_proposal = { proposal_id: params[:id], user_id: current_user[:id] }
      proposal_service = Firebase::Firestore::ProposalService.new(params_proposal)
      @proposal = proposal_service.load_proposal
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def update
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      proposal_service = Firebase::Firestore::ProposalService.new(allowed_parameters)
      proposal_service.process_update
      flash[:success] = I18n.t('dashboard.proposals.messages.success_on_update')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_proposals_url
  end

  private

  def filter_params
    params.permit(:proposal_name, :price, :description, :proposal_id, :proposal_image)
  end

end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController

  def edit
  end

  def update
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      user_service = Firebase::Firestore::UserService.new(allowed_parameters)
      user_service.update_user
      flash[:success] = I18n.t('dashboard.users.messages.success.update_success')
    rescue => error
      flash[:danger] = error.message
    end

    redirect_to dashboard_user_edit_url
  end

  def convert_user_to_artist
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      user_service = Firebase::Firestore::UserService.new(allowed_parameters)
      user_service.transform_listener_in_artist
      flash[:success] = I18n.t('dashboard.users.messages.success.welcome_artist', user_name: current_user[:name])
    rescue => error
      flash[:danger] = error.message
    end

    redirect_to dashboard_url
  end

  private

  def filter_params
    params.permit(:username, :email, :complete_name, :phone_number, :select_gender,
                  :facebook_link, :instagram_link, :twitter_link, :city, :state, :about_me)
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def load_music_status(status)
    Firebase::Firestore::MusicRepository::MUSIC_STATUSES[status]
  end

  def load_music_status_icon(status)
    %w(warning info danger success)[status]
  end
end

app/views/dashboard/home/_albuns.html.erb
<tbody id="tbody-albuns" class="d-none">

  <%= albuns.get do |music| %>

    <tr>
      <th scope="row">
        <div class="media align-items-center">
            <span class="badge badge-dot mx-3">
              <i class="fas fa-music"></i>
            </span>
          <div class="media-body">
              <span class="mb-0 text-sm">
                <%= music.data[:title] %>
              </span>
          </div>
        </div>
      </th>
      <td>
          <span class="badge badge-dot mr-4">
            <i class="bg-warning text-sm"></i>&nbsp;<%= load_music_status(music.data[:status]) %>
          </span>
      </td>
      <td>
        <div class="media align-items-center">
          <div class="media-body text-center">
              <span class="mb-0 text-sm">
                <%= music.data[:message] %>
              </span>
          </div>
        </div>
      </td>
      <td class="text-right">
        <div class="dropdown">
          <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
            <a class="dropdown-item" href="#"><%= I18n.t('dashboard.music.buttons.edit') %></a>
            <a class="dropdown-item" href="#"><%= I18n.t('dashboard.music.buttons.exclude') %></a>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/dashboard/home/_convert_user_to_artist.html.erb
<%= render partial: 'dashboard/partials_shared/header', locals: {
    css_class: 'col-lg-7 col-md-10',
    title: I18n.t('dashboard.user_to_artist.title', user_name: current_user_name),
    description: I18n.t('dashboard.user_to_artist.description')
} %>

<%= render partial: 'dashboard/users/form_edit', locals: {
    action: dashboard_convert_user_to_artist_path,
    button_name: I18n.t('dashboard.user_to_artist.buttons.turn_artist')
} %>

app/views/dashboard/home/_index_content.html.erb
<div class="header dashboard-bg-gradient-primary pb-8 pt-5 pt-md-7">

  <%= render 'layouts/messages' %>

  <div class="container-fluid">
    <div class="header-body">
      <!-- Card stats -->
      <div class="row">
        <div class="col-xl-3 col-lg-6">
          <div class="card card-stats mb-4 mb-xl-0">
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <h5 class="card-title text-uppercase text-muted mb-0"><%= I18n.t('dashboard.home.fields.followers') %></h5>
                  <span class="h2 font-weight-bold mb-0">
                    <%= quantity_followers %>
                  </span>
                </div>
                <div class="col-auto">
                  <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                    <i class="fas fa-user-plus"></i>
                  </div>
                </div>
              </div>
              <p class="mt-3 mb-0 text-muted text-sm">
                <span class="text-nowrap"><%= I18n.t('dashboard.home.fields.total') %></span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-6">
          <div class="card card-stats mb-4 mb-xl-0">
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <h5 class="card-title text-uppercase text-muted mb-0"><%= I18n.t('dashboard.home.fields.sponsorings') %></h5>
                  <span class="h2 font-weight-bold mb-0">
                    <%= quantity_sponsoring %>
                  </span>
                </div>
                <div class="col-auto">
                  <div class="icon icon-shape bg-warning text-white rounded-circle shadow">
                    <i class="fas fa-users"></i>
                  </div>
                </div>
              </div>
              <p class="mt-3 mb-0 text-muted text-sm">
                <span class="text-nowrap"><%= I18n.t('dashboard.home.fields.total') %></span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-6">
          <div class="card card-stats mb-4 mb-xl-0">
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <h5 class="card-title text-uppercase text-muted mb-0"><%= I18n.t('dashboard.home.fields.listeners') %></h5>
                  <span class="h2 font-weight-bold mb-0">
                    <%= quantity_listeners %>
                  </span>
                </div>
                <div class="col-auto">
                  <div class="icon icon-shape bg-yellow text-white rounded-circle shadow">
                    <i class="fas fa-assistive-listening-systems"></i>
                  </div>
                </div>
              </div>
              <p class="mt-3 mb-0 text-muted text-sm">
                <span class="text-nowrap"><%= I18n.t('dashboard.home.fields.per_month') %></span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-lg-6">
          <div class="card card-stats mb-4 mb-xl-0">
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <h5 class="card-title text-uppercase text-muted mb-0"><%= I18n.t('dashboard.home.fields.goal') %></h5>
                  <span class="h2 font-weight-bold mb-0">
                     <%=
                      value = current_user[:goal].present? && current_user[:goal][:goal_current_value].present? ? current_user[:goal][:goal_current_value] : nil
                      format_currency_br(value)
                     %>
                  </span>
                </div>
                <div class="col-auto">
                  <div class="icon icon-shape bg-success text-white rounded-circle shadow">
                    <i class="fas fa-money-bill-wave"></i>
                  </div>
                </div>
              </div>
              <p class="mt-3 mb-0 text-muted text-sm">
                <span class="text-nowrap"><%= I18n.t('dashboard.home.fields.goal_of') %></span>
                <span class="text-success mr-2">
                  <%=
                    value = current_user[:goal].present? ? current_user[:goal][:value] : nil
                    format_currency_br(value)
                  %>
                </span>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'resume_musics' %>

app/views/dashboard/home/_resume_musics.html.erb
<div class="container-fluid mt--7">
  <!-- Table -->
  <div class="row">
    <div class="col">
      <div class="card shadow">
        <div class="card-header border-0 text-uppercase text-muted d-flex justify-content-between">
          <h3 class="mb-0"><%= I18n.t('dashboard.musics.titles.recent_musics') %></h3>

          <div class="btn-group btn-group-toggle w-25" data-toggle="buttons">
<!--            <label class="btn btn-secondary active">-->
<!--              <input type="radio" name="singles" id="singles" autocomplete="off" checked>-->
<!--              &nbsp;<%#= I18n.t('dashboard.musics.buttons.singles') %>-->
<!--            </label>-->
<!--            <label class="btn btn-secondary">-->
<!--              <input type="radio" name="albuns" id="albuns" autocomplete="off">-->
<!--              &nbsp;<%#= I18n.t('dashboard.musics.buttons.albuns') %>-->
<!--            </label>-->
          </div>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col" class="pl-6"><%= I18n.t('dashboard.musics.fields.music_name') %></th>
                <th scope="col"><%= I18n.t('dashboard.musics.fields.status') %></th>
                <th scope="col" class="text-center"><%= I18n.t('dashboard.musics.fields.message') %></th>
                <th scope="col" class="text-center"></th>
              </tr>
            </thead>
            <% if (@singles.present? && @singles.first.present?) ||
                  (@albuns.present? && @albuns.first.present?) %>
              <%= render partial: 'singles', locals: { singles: @singles } %>

              <%#= render partial: 'albuns', locals: { albuns: @albuns } %>
            <% else %>
              <tbody>
                <tr>
                  <th scope="row">
                    <div class="media align-items-center mt-3">
                      <div class="media-body">
                        <span class="mb-0 text-sm">
                          <%= I18n.t('dashboard.musics.fields.no_music') %>
                        </span>
                      </div>
                    </div>
                  </th>
                </tr>
              </tbody>
            <% end %>
          </table>
        </div>

        <div class="container mt--10 pb-5"></div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/home/_singles.html.erb
<tbody id="tbody-singles">

  <% singles.each do |music| %>

    <tr>
      <th scope="row">
        <div class="media align-items-center">
          <a href="#" class="avatar rounded-circle mr-3">
            <img alt="<%= music.data[:title] %>" src="<%= music.data[:image_url] %>">
          </a>
          <div class="media-body">
            <span class="mb-0 text-sm">
              <%= music.data[:title] %>
            </span>
          </div>
        </div>
      </th>
      <td>
        <span class="badge badge-dot mr-4">
          <i class="bg-<%= load_music_status_icon(music.data[:status]) %> text-sm"></i>&nbsp;
          <%= load_music_status(music.data[:status]) %>
        </span>
      </td>
      <td>
        <div class="media align-items-center">
          <div class="media-body text-center">
            <span class="mb-0 text-sm">
              <%= music.data[:message] %>
            </span>
          </div>
        </div>
      </td>
      <td class="text-right">
        <div class="dropdown">
          <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow" x-placement="bottom-end" style="position: absolute; transform: translate3d(-160px, 31px, 0px); top: 0px; left: 0px; will-change: transform;">
            <a class="dropdown-item" href="<%= dashboard_edit_music_path(music.document_id) %>">
              <%= I18n.t('dashboard.musics.buttons.edit') %>
            </a>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/dashboard/home/index.html.erb
<%= render 'dashboard/partials_shared/sidebar' %>

<div class="main-content">

  <%= render 'dashboard/partials_shared/navbar' %>

  <% if is_only_listener? %>
    <%= render 'dashboard/home/convert_user_to_artist' %>
  <% else %>
    <%= render 'dashboard/home/index_content' %>
  <% end %>

  <%= render 'dashboard/partials_shared/footer' %>

</div>