config/routes.rb
Rails.application.routes.draw do

  root to: 'landing_page#index'

  namespace :guest do
    get '/auth/login', to: 'guests#index', as: 'auth_login'
    post '/access-account', to: 'guests#access_account'
  end

  namespace :dashboard do
    get '/', to: 'home#index'

    post 'auth/sign_out', to: 'home#sign_out', as: 'sign_out'

    # users
    get '/user/edit', to: 'users#edit', as: 'user_edit'
    post '/user/update', to: 'users#update', as: 'user_update'
    post '/user/become_artist', to: 'users#convert_user_to_artist', as: 'convert_user_to_artist'

    get '/proposals', to: 'proposals#index', as: 'proposals'
    get '/proposals/new', to: 'proposals#new', as: 'new_proposals'

    post '/proposals/create', to: 'proposals#create', as: 'create_proposals'
    get '/proposals/edit/:id', to: 'proposals#edit', as: 'edit_proposals'
    post '/proposals/update', to: 'proposals#update', as: 'update_proposals'

    get '/musics', to: 'musics#index', as: 'musics'
    get '/musics/new', to: 'musics#new', as: 'new_music'
    post '/musics/create', to: 'musics#create', as: 'create_music'
    get '/musics/edit/:id', to: 'musics#edit', as: 'edit_music'
    post '/musics/update', to: 'musics#update', as: 'update_music'
  end

end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController

  def index
    begin
      music_service = Firebase::Firestore::MusicService.new(user_id: current_user[:id])
      all_songs = music_service.load_all_songs
      @singles = all_songs[:singles]
      @albuns = all_songs[:albuns]
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def sign_out
    reset_session

    redirect_to guest_auth_login_path
  end

end

app/controllers/dashboard/musics_controller.rb
class Dashboard::MusicsController < ApplicationController

  def index
    begin
      music_service = Firebase::Firestore::MusicService.new(user_id: current_user[:id])
      all_songs = music_service.load_all_songs
      @singles = all_songs[:singles]
      @albuns = all_songs[:albuns]
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def new
  end

  def create
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      music_service = Firebase::Firestore::MusicService.new(allowed_parameters)
      music_service.process_creation

      flash[:success] = I18n.t('dashboard.musics.messages.success_on_create')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_musics_url
  end

  def edit
    begin
      music_params = { music_id: params[:id], user_id: current_user[:id] }
      music_service = Firebase::Firestore::MusicService.new(music_params)
      @song = music_service.load_song

      flash[:warning] = I18n.t('dashboard.musics.messages.alert_edit_music')
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def update
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      music_service = Firebase::Firestore::MusicService.new(allowed_parameters)
      music_service.process_update

      flash[:success] = I18n.t('dashboard.musics.messages.success_on_update')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_musics_url
  end

  private

  def filter_params
    params.permit(:music_title, :music_file, :number_track, :image_cover, :music_id)
  end

end

app/controllers/dashboard/proposals_controller.rb
class Dashboard::ProposalsController < ApplicationController

  def index
    begin
      proposal_service = Firebase::Firestore::ProposalService.new(user_id: current_user[:id])
      @all_proposals = proposal_service.load_all_proposals
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def new
  end

  def create
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      proposal_service = Firebase::Firestore::ProposalService.new(allowed_parameters)
      proposal_service.process_creation

      flash[:success] = I18n.t('dashboard.proposals.messages.success_on_create')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_proposals_url
  end

  def edit
    begin
      params_proposal = { proposal_id: params[:id], user_id: current_user[:id] }
      proposal_service = Firebase::Firestore::ProposalService.new(params_proposal)
      @proposal = proposal_service.load_proposal
    rescue =>  error
      flash[:danger] = error.message
    end
  end

  def update
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      proposal_service = Firebase::Firestore::ProposalService.new(allowed_parameters)
      proposal_service.process_update
      flash[:success] = I18n.t('dashboard.proposals.messages.success_on_update')
    rescue =>  error
      flash[:danger] = error.message
    end

    redirect_to dashboard_proposals_url
  end

  private

  def filter_params
    params.permit(:proposal_name, :price, :description, :proposal_id, :proposal_image)
  end

end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController

  def edit
  end

  def update
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      user_service = Firebase::Firestore::UserService.new(allowed_parameters)
      user_service.update_user
      flash[:success] = I18n.t('dashboard.users.messages.success.update_success')
    rescue => error
      flash[:danger] = error.message
    end

    redirect_to dashboard_user_edit_url
  end

  def convert_user_to_artist
    begin
      allowed_parameters = filter_params
      allowed_parameters.merge!(user_id: current_user[:id])
      user_service = Firebase::Firestore::UserService.new(allowed_parameters)
      user_service.transform_listener_in_artist
      flash[:success] = I18n.t('dashboard.users.messages.success.welcome_artist', user_name: current_user[:name])
    rescue => error
      flash[:danger] = error.message
    end

    redirect_to dashboard_url
  end

  private

  def filter_params
    params.permit(:username, :email, :complete_name, :phone_number, :select_gender,
                  :facebook_link, :instagram_link, :twitter_link, :city, :state, :about_me)
  end
end

app/views/dashboard/musics/edit.html.erb
<%= render 'dashboard/partials_shared/sidebar' %>

<div class="main-content">

  <%= render 'dashboard/partials_shared/navbar' %>

  <%= render partial: 'dashboard/partials_shared/header', locals: {
      description: 'Edite suas músicas para que as pessoas possam ouvi-las no Voyce.',
      title: 'Edição de Músicas',
      css_class: 'col-lg-12 col-12'
  } %>

  <%= render partial: 'dashboard/partials_shared/loader' %>

  <div class="container-fluid mt--8">
    <div class="row">

      <%= form_tag dashboard_update_music_path, :id => 'form-action', multipart: true, class: 'd-flex' do %>

        <%= hidden_field_tag :music_id, @song.document_id %>

        <div class="col-xl-8 order-xl-1">
          <div class="card">
            <div class="card-header">
              <div class="row align-items-center text-uppercase">
                <div class="col-8">
                  <h3 class="mb-0">
                    <%= I18n.t('dashboard.musics.titles.update') %>
                  </h3>
                </div>
                <div class="col-4 text-right">
                  <a href="<%= dashboard_musics_path %>" class="btn btn-link text-warning text-right">
                    <%= I18n.t('dashboard.musics.buttons.back') %>
                  </a>
                </div>
              </div>
            </div>
            <div class="card-body">
              <h6 class="heading-small text-muted mb-4">
                <%= I18n.t('dashboard.musics.fields.musics_informations') %>
              </h6>
              <div class="row pl-lg-2 pr-lg-2">
                <div class="col-12">
                  <div class="form-group d-flex flex-row mb-2">
                    <label class="w-25 mr-3" for="music_title">
                      <h4 class="h4 font-weight-600 mb-1">
                        <%= I18n.t('dashboard.musics.fields.title') %>
                      </h4>
                      <h4 class="h6 font-weight-300">
                        <%= I18n.t('dashboard.proposals.fields.required') %>
                      </h4>
                    </label>
                    <div class="input-group mb-4">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="far fa-file-alt"></i>
                        </span>
                      </div>
                      <input class="form-control"
                             name="music_title"
                             id="music_title"
                             placeholder="(Ex.: O dia que não terminou)"
                             type="text"
                             value="<%= @song.data[:title] %>" required>
                    </div>
                  </div>
                </div>

                <div class="col-12">
                  <div class="form-group d-flex flex-row mb-2 justify-content-between">
                    <label class="w-25 mr-3" for="number_track">
                      <div class="h4 font-weight-600 mb-1">
                        <%= I18n.t('dashboard.musics.fields.number_track') %>
                      </div>
                      <div class="h6 font-weight-300">
                        <%= I18n.t('dashboard.proposals.fields.required') %>
                      </div>
                    </label>
                    <div class="input-group mb-4 w-25">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="far fa-file-audio"></i>
                        </span>
                      </div>
                      <input class="form-control"
                             name="number_track"
                             id="number_track"
                             placeholder="1"
                             type="number"
                             min="0"
                             value="<%= @song.data[:position] %>"
                             required>
                    </div>
                  </div>
                </div>

                <div class="col-12 d-flex justify-content-end">
                  <button type="submit" class="btn btn-success w-25" id="button-action">
                    <%= I18n.t('dashboard.musics.buttons.update_music') %>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-4 order-xl-1">
          <div class="card shadow shadow-lg--hover border-0">
            <%= image_tag(@song.data[:image_url], class: 'card-img-top') %>
          </div>
        </div>

      <% end %>
    </div>

    <%= render 'dashboard/partials_shared/footer' %>

  </div>

</div>

<%= javascript_pack_tag 'additionals/disable_buttons' %>

app/views/dashboard/musics/index.html.erb
<%= render 'dashboard/partials_shared/sidebar' %>

<div class="main-content">

  <%= render 'dashboard/partials_shared/navbar' %>

  <%= render partial: 'dashboard/partials_shared/header', locals: {
      description: 'Aqui você pode visualizar e editar suas músicas.',
      title: 'Gerencie suas músicas',
      css_class: 'col-lg-12 col-12'
  } %>

  <div class="container-fluid">

    <div class="row">
      <div class="col">
        <div class="card shadow">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <div class="col-8 text-uppercase">
                <h3 class="mb-0">
                  <%= I18n.t('dashboard.musics.titles.musics') %>
                </h3>
              </div>
              <div class="col-4 text-right">
                <a href="<%= dashboard_new_music_path %>" class="btn btn-1 btn-outline-success">
                  <%= I18n.t('dashboard.musics.buttons.upload_music') %>
                </a>
              </div>
            </div>
          </div>

          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col" class="pl-6" style="width: 30vw;"><%= I18n.t('dashboard.musics.fields.music_name') %></th>
                <th scope="col" style="width: 5vw;"><%= I18n.t('dashboard.musics.fields.status') %></th>
                <th scope="col" class="text-left" style="width: 60vw;"><%= I18n.t('dashboard.musics.fields.message') %></th>
                <th scope="col" style="width: 5vw;"></th>
              </tr>
            </thead>
            <% if @singles.present? && @singles.first.present? %>
              <%= render partial: 'dashboard/home/singles', locals: { singles: @singles } %>
            <% else %>
              <tbody>
              <tr>
                <th scope="row">
                  <div class="media align-items-center mt-3">
                    <div class="media-body">
                        <span class="mb-0 text-sm">
                          <%= I18n.t('dashboard.musics.fields.no_music') %>
                        </span>
                    </div>
                  </div>
                </th>
              </tr>
              </tbody>
            <% end %>
          </table>

          <!-- Pagination -->
          <div class="card-footer py-4">
            <nav class="d-flex justify-content-end" aria-label="...">

            </nav>
          </div>
        </div>
      </div>
    </div>

    <%= render 'dashboard/partials_shared/footer' %>

  </div>

</div>

app/views/dashboard/musics/new.html.erb
<%= render 'dashboard/partials_shared/sidebar' %>

<div class="main-content">

  <%= render 'dashboard/partials_shared/navbar' %>

  <%= render partial: 'dashboard/partials_shared/header', locals: {
      description: 'Envie suas músicas para que as pessoas possam ouvi-las no Voyce.',
      title: 'Upload de Músicas',
      css_class: 'col-lg-12 col-12'
  } %>

  <%= render partial: 'dashboard/partials_shared/loader' %>

  <div class="container-fluid mt--8">
    <div class="row">

      <%= form_tag dashboard_create_music_path, :id => 'form-action', multipart: true, class: 'd-flex' do %>

        <div class="col-xl-8 order-xl-1">
          <div class="card">
            <div class="card-header">
              <div class="row align-items-center text-uppercase">
                <div class="col-8">
                  <h3 class="mb-0">
                    <%= I18n.t('dashboard.musics.titles.upload') %>
                  </h3>
                </div>
                <div class="col-4 text-right">
                  <a href="<%= dashboard_musics_path %>" class="btn btn-link text-warning text-right">
                    <%= I18n.t('dashboard.musics.buttons.back') %>
                  </a>
                </div>
              </div>
            </div>
            <div class="card-body">
              <h6 class="heading-small text-muted mb-4">
                <%= I18n.t('dashboard.musics.fields.musics_informations') %>
              </h6>
              <div class="row pl-lg-2 pr-lg-2">
                <div class="col-12">
                  <div class="form-group d-flex flex-row mb-2">
                    <label class="w-25 mr-3" for="music_title">
                      <h4 class="h4 font-weight-600 mb-1">
                        <%= I18n.t('dashboard.musics.fields.title') %>
                      </h4>
                      <h4 class="h6 font-weight-300">
                        <%= I18n.t('dashboard.proposals.fields.required') %>
                      </h4>
                    </label>
                    <div class="input-group mb-4">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="far fa-file-alt"></i>
                        </span>
                      </div>
                      <input class="form-control"
                             name="music_title"
                             id="music_title"
                             placeholder="(Ex.: O dia que não terminou)"
                             type="text" required>
                    </div>
                  </div>
                </div>

                <div class="col-12">
                  <div class="form-group d-flex flex-row mb-2 justify-content-between">
                    <label class="w-25 mr-3">
                      <div class="h4 font-weight-600 mb-1">
                        <%= I18n.t('dashboard.musics.buttons.select_music') %>
                      </div>
                      <div class="h6 font-weight-300">
                        <%= I18n.t('dashboard.proposals.fields.required') %>
                      </div>
                    </label>

                    <div class="custom-file w-50">
                      <input type="file" class="custom-file-input" id="music_file" name="music_file">
                      <label class="custom-file-label"
                             for="music_file">
                        <%= I18n.t('dashboard.musics.buttons.select_music') %>
                      </label>
                    </div>
                  </div>
                </div>

                <div class="col-12">
                  <div class="form-group d-flex flex-row mb-2 justify-content-between">
                    <label class="w-25 mr-3" for="number_track">
                      <div class="h4 font-weight-600 mb-1">
                        <%= I18n.t('dashboard.musics.fields.number_track') %>
                      </div>
                      <div class="h6 font-weight-300">
                        <%= I18n.t('dashboard.proposals.fields.required') %>
                      </div>
                    </label>
                    <div class="input-group mb-4 w-25">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="far fa-file-audio"></i>
                        </span>
                      </div>
                      <input class="form-control"
                             name="number_track"
                             id="number_track"
                             placeholder="1"
                             type="number"
                             min="0"
                             required>
                    </div>
                  </div>
                </div>

                <div class="col-12 d-flex justify-content-end">
                  <button type="submit" class="btn btn-success w-25" id="button-action">
                    <%= I18n.t('dashboard.musics.buttons.upload_music') %>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-4 order-xl-1">
          <div class="card shadow shadow-lg--hover p-4">
            <%= image_tag('music-icon.svg', class: 'card-img-top') %>
            <div class="custom-file d-flex justify-content-center my-3">
              <input type="file" class="custom-file-input d-none" id="image_cover" name="image_cover">
              <button type="button" class="btn btn-outline-primary w-50" id="anchor_upload">
                <i class="fas fa-upload"></i>&nbsp;
                <%= I18n.t('dashboard.musics.buttons.select_image') %>
              </button>
            </div>
          </div>
        </div>

      <% end %>
    </div>

    <%= render 'dashboard/partials_shared/footer' %>

  </div>

</div>

<%= javascript_pack_tag 'additionals/disable_buttons' %>